// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhoydbjcneodbgepfyho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZob3lkYmpjbmVvZGJnZXBmeWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzUzOTIsImV4cCI6MjA2MDM1MTM5Mn0.lcFDD1HYqZXnfVBNCyysdMmQl_ijQbx0i3H4MY_Si6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);